config/routes.rb
Rails.application.routes.draw do
  root to: "static_pages#root"
  get '/friendships/search', to: "friendships#search", as: "search_friend"
  resources :users, except: [:index] do 
    resources :posts, only: [:create, :update, :destroy]
    resources :friendships, only: [:destroy]
   
    post '/friendships', to: "friendships#send_request", as: "request_friend"
    patch '/friendships/:left_friend_id', to: "friendships#approve", as: "approve_friend"
  end

  resources :sessions, only: [:new, :create, :destroy]
  delete '/sessions/sign_out_all', to: "sessions#sign_out_all_sessions", as: "sign_out_all"

  namespace :api, defaults: { format: :json } do
    resources :sessions, only: [:new, :create, :destroy]
    delete '/sessions/sign_out_all', to: "sessions#sign_out_all_sessions", as: "sign_out_all"

    get '/friendships/search', to: "friendships#search", as: "search_friend"
    resources :users do 
      resources :posts, only: [:index, :show, :create, :update, :destroy]
      resources :friendships, only: [:destroy]
     
      post '/friendships', to: "friendships#send_request", as: "request_friend"
      patch '/friendships/:left_friend_id', to: "friendships#approve", as: "approve_friend"
    end

     root to: "static_pages#root"
     post '/guest_sign_in', to: "sessions#guest_sign_in", as: "guest_sign_in"
  end

end

app/views/layouts/_header.html.haml
#header.clearfix
	
	.title
		Social App Sample
	.container.clearfix
		.search-box
			%form{ :action => search_friend_url, :method => "GET"}
				%label{:for => "query"} Search for new friends:
				%input{:type => 'text', :name => "query", :class_name => "query-box"}
				%input{:type => 'submit', :value => "Search", :class => "button"}
		.name
			Signed In:
			%strong 
				= link_to "#{current_user.full_name}", user_url(current_user)
		.btn
			= link_to "Sign Out", session_url(current_user), :method => :delete
		.btn
			= link_to "Sign Out All Sessions", sign_out_all_url, :method => :delete

app/views/layouts/_sidebar.html.haml
#sidebar.clearfix
	%h4 user stat:
	.profile-info
		.current-user
			= render "shared/friend", :friend => current_user

	%h4 current friends:
	.friends-container
		%ol
			- @friends.each do |friend|
				%li.clearfix
					= render "shared/friend", :friend => friend

	%h4 pending friends:
	.friends-container
		%ol
			- @pending_friends.each do |pending_friend|
				%li.clearfix
					= render "shared/friend", :friend => pending_friend
					= link_to "approve", user_approve_friend_url(:user_id => current_user.id, :left_friend_id => pending_friend.id ), :method => :patch
					= link_to "deny", user_friendship_url(:user_id => current_user.id, :left_friend_id => pending_friend.id, :id => 1), :method => :delete

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title SocialApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %script{:id => "current-user-id", :data => { :id => signed_in? ? current_user.id : 0} }

  %body   
    - unless flash[:errors].nil?
      %ol
        - flash[:errors].each do |error|
          %li #{error}
    - if signed_in?
      / = render "layouts/header"
      / = render "layouts/sidebar"
      #main-container
        #main
          = yield
    - else
      #root
        = yield

    
